# Generated by Django 5.1.3 on 2024-11-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
        ('user', '0002_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tags',
            field=models.ManyToManyField(related_name='user_profiles', to='nlp.tag'),
        ),
    ]
