# Generated by Django 5.1.3 on 2024-11-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
        ('user', '0003_userprofile_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tags',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='soft_tags',
            field=models.ManyToManyField(related_name='user_profiles_soft', to='nlp.tag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='strict_tags',
            field=models.ManyToManyField(related_name='user_profiles_strict', to='nlp.tag'),
        ),
    ]
